### ISSUE TITLE
Cosmic Bit-Flip got me in infinite loop

### ISSUE THREAD

**Issue by zopad** [Matyasmester/Prisoner-Dilemma#1]
https://github.com/Matyasmester/Prisoner-Dilemma/blob/f1301f9fe6902802421661450be7422d8babb99e/Prisoner%20Dilemma/Program.cs#L64

Hello, when I was running your program my PC got hit by a cosmic ray resulting in an infinite loop. My PC overheated and you should pay for the damages. 😎😎😎😎😎😎😎😍🥰😘😅😆

**Comment by Matyasmester** [comment]
kinkaku and ginkaku

**Comment by Matyasmester** [comment]
Amúgy skill issue @zopad

**Comment by zopad** [comment]
> Amúgy skill issue @zopad

Mi a faszt csinálsz és minek? 
![Rick-Astley-Never-Gonna-Give-You-Up_png_92](https://github.com/Matyasmester/Prisoner-Dilemma/assets/6132366/0e5b2473-c02c-4f89-97e0-604601c2eef6)
